### PR TITLE
Tokenizer refactor

### PR DESCRIPTION
**Pull request by maddymakesgames**
Refactors JottTokenizer to use switch expressions instead of if/else chains and comments most of the file.
Also does some minor refactors to make things feel more idiomatic.

Feel free to revert or correct any changes.

Still passes all tokenizer tests.

### CODE REVIEW

**Comment by maddymakesgames** [comment]
oh also idk if this is actually a thing but I might've switched the file from CRLF to LF. I don't think this should cause any issues but something was complaining about line endings somewhere so I might've switched them.

**Comment by powerboat9** [comment]
Probably want to change the line endings back to CRLF for now, just to get a proper diff

**Review by powerboat9 — APPROVED** [review]

**Comment by powerboat9** [comment]
Doesn't look like the line endings changed, but not the end of the world

**Review by dax-dot-gay — APPROVED** [review]
LGTM, gonna comment now

**Pull request merged**
